# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for NetworkAPI
  pod 'AFNetworking', '~> 2.5'	
  pod 'IGListKit', '~> 3.4.0'

  pod 'SDWebImage', '~> 5.0'
  target 'NetworkAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NetworkAPIUITests' do
    # Pods for testing
  end


end
