# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CalculatorBM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CalculatorBM
	platform :ios, '8.0'
        pod 'SDWebImage', '~> 5.0'

 
  target 'CalculatorBMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CalculatorBMUITests' do
    # Pods for testing
  end

end
