# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MessageZ' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessageZ
  pod 'SDWebImage', '~> 5.0'

  target 'MessageZTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MessageZUITests' do
    # Pods for testing
  end

end
