# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'JsonEditorTool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JsonEditorTool
     pod 'AFNetworking', '~> 3.0', :modular_headers => true
     pod 'IGListKit', '~> 3.4.0', :modular_headers => true
     pod 'FBSDKShareKit', '~> 4.36.0', :modular_headers => true
     pod 'DLRadioButton', '~> 1.4', :modular_headers => true
    


  target 'JsonEditorToolTests' do
    inherit! :search_paths
    # Pods for testing
     
  end

  target 'JsonEditorToolUITests' do
    # Pods for testing
  end

end
