# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuanSuTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuanSuTest
	pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

  target 'QuanSuTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuanSuTestUITests' do
    # Pods for testing
  end

end
