# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JsonEditorTool_BM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JsonEditorTool_BM
     pod 'AFNetworking', '~> 3.0'
     pod 'IGListKit', '~> 3.4.0'
     pod 'FBSDKShareKit', '~> 4.36.0'
     pod 'DLRadioButton', '~> 1.4'
  target 'JsonEditorTool_BMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JsonEditorTool_BMUITests' do
    # Pods for testing
  end

end
