# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestFramework2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestFramework2
   pod 'SDWebImage', '~> 5.0'

  target 'TestFramework2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestFramework2UITests' do
    # Pods for testing
  end

end
