# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoIGLK1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demoIGLK1
  pod 'SDWebImage', '~> 5.0'
  target 'demoIGLK1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demoIGLK1UITests' do
    # Pods for testing
  end

end
